---
title: "real data calibration"
author: "Yunqi Yang"
date: "7/16/2024"
output: html_document
---

# Old plot
```{r fig.height = 8, fig.width=8}

pdf("/Users/nicholeyang/downloads/simulation-calibrated-mr/output/real_data_calibration.pdf", height = 8, width = 10)
par(mfrow = c(2,2))
## Trio data
bmi = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/trio_calibration_bmi.rds")
sbp = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/trio_calibration_sbp.rds")
dbp = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/trio_calibration_dbp.rds")
diabetes = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/trio_calibration_diabetes.rds")
edu = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/trio_calibration_education_yrs.rds")

dat = list(bmi, sbp, dbp, diabetes, edu)

for (i in 1:length(dat)){
  dat[[i]] = as.data.frame(dat[[i]])
  dat[[i]][, c(3:8)] = apply(dat[[i]][, c(3:8)], 2, as.numeric)
}


diff = sapply(1:5, function(i) dat[[i]]$cali - dat[[i]]$raw)
vr =  sapply(1:5, function(i) 1 - dat[[i]]$cali.var/dat[[i]]$raw.var)
colnames(diff) = c("BMI", "SBP", "DBP", "Diabetes", "EduYrs")
colnames(vr) = c("BMI", "SBP", "DBP", "Diabetes", "EduYrs")

boxplot(diff,xlab = "(a)", ylab = "Calibrated estimator - Raw estimator", 
        names = colnames(diff), pch = 20, cex = 0.6, col = colors[1:5])
mtext("Trio data", side = 3, adj = 0, line = 1)
boxplot(vr, xlab = "(b)", ylab = "Estimated variance reduction",names = colnames(diff), pch = 20, cex = 0.6)


## sibling data 
bmi = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_bmi.rds")
sbp = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_sbp.rds")
dbp = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_dbp.rds")
diabetes = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_diabetes.rds")
edu = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_education_yrs.rds")

dat = list(edu, bmi, sbp, dbp, diabetes)
for (i in 1:length(dat)){
  dat[[i]] = as.data.frame(dat[[i]])
  dat[[i]][, c(3:8)] = apply(dat[[i]][, c(3:8)], 2, as.numeric)
}

diff = sapply(1:5, function(i) dat[[i]]$cali - dat[[i]]$raw)
vr =  sapply(1:5, function(i) 1 - dat[[i]]$cali.var/dat[[i]]$raw.var)
colnames(diff) = c("EduYrs", "BMI", "SBP", "DBP", "Diabetes")
colnames(vr) = c("EduYrs", "BMI", "SBP", "DBP", "Diabetes")

pheno.cor = c(0.355, 0.284, 0.202, 0.148, 0.091)
theo_vr = (1-0.5)/2*(1-pheno.cor)/(1+0.5*pheno.cor)

boxplot(diff, xlab = "(c)", ylab = "Calibrated estimator - Raw estimator", 
        names = colnames(diff), pch = 20, cex = 0.6)
mtext("Sibling data", side = 3, adj = 0, line = 1)
boxplot(vr, xlab = "(d)", ylab = "Estimated variance reduction",names = colnames(vr), pch = 20, cex = 0.6)
points(1:length(theo_vr), theo_vr, col = "red", pch = 4)
```

# new plot
```{r}
# Load the required library
library(ggplot2)
library(reshape2)
library(gridExtra)
```

```{r}
## Trio data
bmi = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/trio_calibration_bmi.rds")
sbp = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/trio_calibration_sbp.rds")
dbp = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/trio_calibration_dbp.rds")
diabetes = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/trio_calibration_diabetes.rds")
edu = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/trio_calibration_education_yrs.rds")

dat = list(bmi, sbp, dbp, diabetes, edu)

for (i in 1:length(dat)){
  dat[[i]] = as.data.frame(dat[[i]])
  dat[[i]][, c(3:8)] = apply(dat[[i]][, c(3:8)], 2, as.numeric)
}


diff = sapply(1:5, function(i) dat[[i]]$cali - dat[[i]]$raw)
vr =  sapply(1:5, function(i) 1 - dat[[i]]$cali.var/dat[[i]]$raw.var)
colnames(diff) = c("BMI", "SBP", "DBP", "Diabetes", "EduYrs")
colnames(vr) = c("BMI", "SBP", "DBP", "Diabetes", "EduYrs")

# Convert the matrices to long format for ggplot2
diff_long <- melt(diff)
vr_long <- melt(vr)

colors <- c("EduYrs" = "#66C2A5", 
            "BMI" = "#FC8D62", 
            "SBP" = "#8DA0CB", 
            "DBP" = "#E78AC3", 
            "Diabetes" = "#A6D854")


# Rename the columns for easier reference
colnames(diff_long) <- c("Observation", "Trait", "Value")
colnames(vr_long) <- c("Observation", "Trait", "Value")

# Plotting the diff boxplot
p1 <- ggplot(diff_long, aes(x = Trait, y = Value, fill = Trait)) +
  geom_boxplot() +
  scale_fill_manual(values = colors) +
  labs(x = "(a)", y = "Calibrated estimator - Raw estimator", title = "Trio data") +
  theme_minimal()

# Plotting the vr boxplot
p2 <- ggplot(vr_long, aes(x = Trait, y = Value, fill = Trait)) +
  geom_boxplot() +
  scale_fill_manual(values = colors) +
  labs(x = "(b)", y = "Estimated variance reduction") +
  theme_minimal() + 
  theme(legend.position = "none")

```

```{r}
## sibling data 
bmi = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_bmi.rds")
sbp = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_sbp.rds")
dbp = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_dbp.rds")
diabetes = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_diabetes.rds")
edu = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_education_yrs.rds")

dat = list(edu, bmi, sbp, dbp, diabetes)
for (i in 1:length(dat)){
  dat[[i]] = as.data.frame(dat[[i]])
  dat[[i]][, c(3:8)] = apply(dat[[i]][, c(3:8)], 2, as.numeric)
}

diff = sapply(1:5, function(i) dat[[i]]$cali - dat[[i]]$raw)
vr =  sapply(1:5, function(i) 1 - dat[[i]]$cali.var/dat[[i]]$raw.var)
colnames(diff) = c("EduYrs", "BMI", "SBP", "DBP", "Diabetes")
colnames(vr) = c("EduYrs", "BMI", "SBP", "DBP", "Diabetes")

pheno.cor = c(0.355, 0.284, 0.202, 0.148, 0.091)
theo_vr = (1-0.5)/2*(1-pheno.cor)/(1+0.5*pheno.cor)


# Convert the matrices to long format for ggplot2
diff_long <- melt(diff)
vr_long <- melt(vr)

# Rename the columns for easier reference
colnames(diff_long) <- c("Observation", "Trait", "Value")
colnames(vr_long) <- c("Observation", "Trait", "Value")

colors <- c("EduYrs" = "#66C2A5", 
            "BMI" = "#FC8D62", 
            "SBP" = "#8DA0CB", 
            "DBP" = "#E78AC3", 
            "Diabetes" = "#A6D854")

p3 <- ggplot(diff_long, aes(x = Trait, y = Value, fill = Trait)) +
  geom_boxplot() +
  scale_fill_manual(values = colors) +
  labs(x = "(c)", y = "Calibrated estimator - Raw estimator", title = "Sibling data") +
  theme_minimal()


p4 <- ggplot(vr_long, aes(x = Trait, y = Value, fill = Trait)) +
  geom_boxplot() +
  scale_fill_manual(values = colors) +
  labs(x = "(d)", y = "Estimated variance reduction") +
  theme_minimal() +
  theme(legend.position = "none")


pheno.cor = c(0.355, 0.284, 0.202, 0.148, 0.091)
theo_vr = (1-0.5)/2*(1-pheno.cor)/(1+0.5*pheno.cor)
theo_vr_df <- data.frame(
  Trait = factor(c("EduYrs", "BMI", "SBP", "DBP", "Diabetes"), 
                 levels = c("EduYrs", "BMI", "SBP", "DBP", "Diabetes")),
  Value = theo_vr
)


p4 <- p4 + 
  geom_point(data = theo_vr_df, aes(x = Trait, y = Value), color = "red", shape = 4, size = 3)
p4


```

```{r}
combined_plot <- grid.arrange(p1, p2, p3, p4, ncol = 2, nrow = 2)
ggsave("/Users/nicholeyang/downloads/simulation-calibrated-mr/output/real_data_calibration_gg.pdf", combined_plot, width = 10, height = 10)

```

