---
title: "paper_plot_gg"
output: html_document
date: '2025-04-06'
---

```{r}
library(latex2exp)
library(ggplot2)
library(latex2exp)
library(dplyr)
library(tidyr)
library(gridExtra)
```

```{r}
compute_theo_vr <- function(sigma2, rho, r, b2, sample_size_ratio){
  vr = sigma2*(1-rho)^2*(1-r)/((sigma2 + b2*(1-r^2))*(1+sample_size_ratio - 2*rho))/2
  return(vr)
}

theo_vr = compute_theo_vr(1, 0, 0, 0, 0.1)
```

```{r}
combine_single_snp_stat = function(cond_indx, snp_indx, data.list, column_names){
  res = lapply(cond_indx, function(ind) data.list[[ind]][snp_indx, column_names])
  dat_combined = do.call(rbind, res)
  return(dat_combined)
}
```


#### Trio VR
```{r}
nrep = 500
### Trio data
res = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim_parametric202404/trio_linear/res.rds")

r1 = unique(res$sim_data.r1)
p = 10
empirical_var_raw = matrix(NA, ncol = p, nrow = length(r1))
empirical_var_cali = matrix(NA, ncol = p, nrow = length(r1))

for (i in 1:p){
  # result merged for different r2 values 
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res$sim_data.r1 == r1[k] & res$fit.method == "calibrated_model_T"), i, data.list = res$fit.sumstat, column_names = c("Y1.raw")))
  dat_estimator <- do.call(cbind, snp_dat_list)
  empirical_var_raw[, i] = apply(dat_estimator[1:nrep, ], 2, var)
  
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res$sim_data.r1 == r1[k] & res$fit.method == "calibrated_model_T"), i, data.list = res$fit.sumstat, column_names = c("Y1.cali")))
  dat_estimator <- do.call(cbind, snp_dat_list)
  empirical_var_cali[, i] = apply(dat_estimator[1:nrep, ], 2, var)
}

vr = (empirical_var_raw - empirical_var_cali) / empirical_var_raw
rownames(vr) = r1
```

```{r}
# Reshape the vr matrix to long format
df_trio <- as.data.frame(vr)
df_trio$r1 <- rownames(vr)

df_trio_long <- df_trio %>%
  pivot_longer(cols = -r1, names_to = "snp", values_to = "vr") %>%
  mutate(r1 = factor(r1, levels = c("0", "0.1", "0.5")))

p1 <- ggplot(df_trio_long, aes(x = r1, y = vr, fill = r1)) +
  geom_boxplot(color = "black", width = 0.5, outlier.size = 0.5) +
  geom_hline(yintercept = theo_vr, linetype = "dashed", color = "red") +
  scale_fill_manual(values = c("0" = "#a6cee3", "0.1" = "#a6cee3", "0.5" = "#a6cee3")) +
  labs(
    x = expression("Nurture effect size (" * r[1] * " value)"),
    y = "Empirical variance reduction",
    title = "Trio data"
  ) +
  ylim(0, 1) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")

```

#### Sibling data
```{r}
### Sibling data
phe_seq = seq(0, 1, by = 0.01)
theo_vr = (1-0.5)/2*(1-phe_seq)/(1+0.5*phe_seq+ 0.1)
dat = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim_parametric202404/sibling_linear_separate/res.rds")

p = 10
r1 = unique(dat[[1]]$sim_data.r1)
sigs = unique(sapply(1:4, function(i) dat[[i]]$sim_data.sig))

combinations = expand.grid(r1 = r1, sigs = sigs)
ncomb = nrow(combinations)
combinations$pheno.cor = rep(NA, ncomb)

empirical_var_raw = matrix(NA, ncol = p, nrow = ncomb)
empirical_var_cali = matrix(NA, ncol = p, nrow = ncomb)


for (i in 1:p){
  for (k in 1:nrow(combinations)){
    sig = combinations[k, 2]
    if (sig == 1){sig.indx = 1}
    if (sig == 3){sig.indx = 2}
    if (sig == 6){sig.indx = 3}
    if (sig == 10){sig.indx = 4}
    res = dat[[sig.indx]]
    dat_indx = which(res$sim_data.r1 == combinations[k, 1] & res$sim_data.sig == sig & res$fit.method == "calibrated")
    combinations[k, 3] = mean(unlist(lapply(res$sim_data.cor_pheno[dat_indx[1:nrep]], function(x) x[1])))
    empirical_var_raw[k, i] = var(unlist(lapply(res$fit.sumstat[dat_indx[1:nrep]], function(x) x[i, "Y1.raw"])))
    empirical_var_cali[k, i] = var(unlist(lapply(res$fit.sumstat[dat_indx[1:nrep]], function(x) x[i, "Y1.cali"])))
  }
}

combinations$pheno.cor = combinations$pheno.cor
vr = (empirical_var_raw - empirical_var_cali)/empirical_var_raw
```

```{r}

df_sib <- data.frame(
  pheno_cor = rep(combinations$pheno.cor, times = p),
  vr = as.vector(vr)
)

# Prepare theoretical line
df_theo <- data.frame(
  phe_seq = phe_seq,
  theo_vr = theo_vr
)

p2 <- ggplot(df_sib, aes(x = pheno_cor, y = vr)) +
  geom_point(size = 0.5, alpha = 0.7) +
  geom_line(data = df_theo, aes(x = phe_seq, y = theo_vr), color = "red", linetype = "dashed") +
  labs(
    x = "Phenotypic correlation between siblings",
    y = "Empirical variance reduction",
    title = "Sibling data"
  ) +
  xlim(0, 0.8) +
 # ylim(0, 1) +
  theme_minimal(base_size = 14)

```


### Logistic regression Trio data

```{r}
nrep = 500
### Trio data
theo_vr = compute_theo_vr(1, 0, 0, 0, 0.1)
res = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim_parametric202404/trio_logistic_cutoff1.5/res.rds")
r1 = unique(res$sim_data.r1)
p = 10
empirical_var_raw = matrix(NA, ncol = p, nrow = length(r1))
empirical_var_cali = matrix(NA, ncol = p, nrow = length(r1))

for (i in 1:p){
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res$sim_data.r1 == r1[k] & res$fit.method == "calibrated"), i, data.list = res$fit.sumstat, column_names = c("Y1.raw")))
  dat_estimator <- do.call(cbind, snp_dat_list)
  empirical_var_raw[, i] = apply(dat_estimator[1:nrep, ], 2, var)
  
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res$sim_data.r1 == r1[k] & res$fit.method == "calibrated"), i, data.list = res$fit.sumstat, column_names = c("Y1.cali")))
  dat_estimator <- do.call(cbind, snp_dat_list)
  empirical_var_cali[, i] = apply(dat_estimator[1:nrep, ], 2, var)
}

vr = (empirical_var_raw - empirical_var_cali) / empirical_var_raw
rownames(vr) = r1
```

```{r}
df_trio <- as.data.frame(vr)
df_trio$r1 <- rownames(vr)

df_trio_long <- df_trio %>%
  pivot_longer(cols = -r1, names_to = "snp", values_to = "vr") %>%
  mutate(r1 = factor(r1, levels = c("0", "0.1", "0.5")))

# Plot
p3 <- ggplot(df_trio_long, aes(x = r1, y = vr, fill = r1)) +
  geom_boxplot(width = 0.5, color = "black", outlier.size = 0.5) +
  geom_hline(yintercept = theo_vr, color = "red", linetype = "dashed") +
  scale_fill_manual(values = c("0" = "#a6cee3", "0.1" = "#a6cee3", "0.5" = "#a6cee3")) +
  labs(
    x = expression("Nurture effect size (" * r[1] * " value)"),
    y = "Empirical variance reduction"
  ) +
  ylim(0, 1) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")
```


```{r}
### Sibling data
phe_seq = seq(0, 1, by = 0.01)
theo_vr = (1-0.5)/2*(1-phe_seq)/(1+0.5*phe_seq+ 0.1)
dat = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim_parametric202404/sibling_logistic_separate/res.rds")

p = 10
r1 = unique(dat[[1]]$sim_data.r1)
sigs = unique(sapply(1:4, function(i) dat[[i]]$sim_data.sig))

combinations = expand.grid(r1 = r1, sigs = sigs)
ncomb = nrow(combinations)
combinations$pheno.cor = rep(NA, ncomb)

empirical_var_raw = matrix(NA, ncol = p, nrow = ncomb)
empirical_var_cali = matrix(NA, ncol = p, nrow = ncomb)


for (i in 1:p){
  for (k in 1:nrow(combinations)){
    sig = combinations[k, 2]
    if (sig == 1){sig.indx = 1}
    if (sig == 3){sig.indx = 2}
    if (sig == 6){sig.indx = 3}
    if (sig == 10){sig.indx = 4}
    res = dat[[sig.indx]]
    dat_indx = which(res$sim_data.r1 == combinations[k, 1] & res$sim_data.sig == sig & res$fit.method == "calibrated")
    combinations[k, 3] = mean(unlist(lapply(res$sim_data.cor_pheno[dat_indx[1:nrep]], function(x) x[1])))
    empirical_var_raw[k, i] = var(unlist(lapply(res$fit.sumstat[dat_indx[1:nrep]], function(x) x[i, "Y1.raw"])))
    empirical_var_cali[k, i] = var(unlist(lapply(res$fit.sumstat[dat_indx[1:nrep]], function(x) x[i, "Y1.cali"])))
  }
}

combinations$pheno.cor = round(combinations$pheno.cor,2)
vr = (empirical_var_raw - empirical_var_cali)/empirical_var_raw
```

```{r}
# Prepare empirical and theoretical data
df_sib <- data.frame(
  pheno_cor = rep(combinations$pheno.cor, times = p),
  vr = as.vector(vr)
)

df_theo <- data.frame(
  phe_seq = phe_seq,
  theo_vr = theo_vr
)

# Plot
p4 <- ggplot(df_sib, aes(x = pheno_cor, y = vr)) +
  geom_point(size = 0.6, alpha = 0.7) +
  geom_line(data = df_theo, aes(x = phe_seq, y = theo_vr), color = "red", linetype = "dashed") +
  labs(
    x = "Phenotypic correlation between siblings",
    y = "Empirical variance reduction"
  ) +
  xlim(0, 0.8) +
  theme_minimal(base_size = 14)


```

```{r}
ggsave("/project2/mstephens/yunqiyang/calibrated_mr/simulation-calibrated-mr/output/sim_calibration.pdf",
       plot = grid.arrange(p1, p2, p3, p4, ncol = 2),
       width = 10, height = 8)
```

