---
title: "sim_mr_ggplot"
output: html_document
date: '2025-04-08'
---

```{r}
library(latex2exp)
```

### 1. trio linear regression
```{r}
dat = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim_parametric202404/trio_linear/res_mr.rds")
r1 = unique(dat$sim_data.r1) 
r2 = unique(dat$sim_data.r2) 
method = c("calibrated_model_T", "adj_uncalibrated", "unadj_ext")
mr_method = c("ivw", "mr.raps")

# 1. trio data
# IVW
n_rep = 500
combinations <- rbind(c(0, 0), c(0.1, 0), c(0.5, 0), c(0.5, 0.1), c(0.5, 0.5))
colnames(combinations) = c("r1", "r2")

output = c()
for (i in 1:nrow(combinations)){
  res = dat[dat$sim_data.r1 == combinations[i, 1] & dat$sim_data.r2 == combinations[i, 2] & dat$mr.mr_method == "ivw", ]
  val = cbind(res$mr.point_est[res$fit.method == "calibrated_model_T"][1:n_rep],
              res$mr.point_est[res$fit.method == "adj_uncalibrated"][1:n_rep],
              res$mr.point_est[res$fit.method == "unadj_ext"][1:n_rep])
  output = cbind(output, val)
}

means <- colMeans(output)
ses <- apply(output, 2, sd)
ncomb = nrow(combinations)

methods <- rep(c("Calibrated", "Raw", "External"), times = ncomb)
group_labels <- apply(combinations, 1, function(x) paste0("(", x[1], ",", x[2], ")"))
group <- rep(group_labels, each = 3)

# Prepare data frame for IVW
df_ivw <- data.frame(
  method = factor(methods, levels = c("Calibrated", "Raw", "External")),
  group = factor(group, levels = group_labels),
  mean = means,
  se = ses
) %>%
  mutate(
    lower = mean - 1.96 * se,
    upper = mean + 1.96 * se,
    model = "IVW"
)

### mr.raps
n_rep = 500
combinations <- rbind(c(0, 0), c(0.1, 0), c(0.5, 0), c(0.5, 0.1), c(0.5, 0.5))
colnames(combinations) = c("r1", "r2")

output = c()
for (i in 1:nrow(combinations)){
  res = dat[dat$sim_data.r1 == combinations[i, 1] & dat$sim_data.r2 == combinations[i, 2] & dat$mr.mr_method == "mr.raps", ]
  val = cbind(res$mr.point_est[res$fit.method == "calibrated_model_T"][1:n_rep],
              res$mr.point_est[res$fit.method == "adj_uncalibrated"][1:n_rep],
              res$mr.point_est[res$fit.method == "unadj_ext"][1:n_rep])
  output = cbind(output, val)
}

means <- colMeans(output)
ses <- apply(output, 2, sd)
ncomb = nrow(combinations)

# For MR.RAPS
df_mrraps <- data.frame(
  method = factor(methods, levels = c("Calibrated", "Raw", "External")),
  group = factor(group, levels = group_labels),
  mean = means,   # from MR.RAPS
  se = ses
) %>%
  mutate(
    lower = mean - 1.96 * se,
    upper = mean + 1.96 * se,
    model = "MR.RAPS"
)


```

```{r}
p1 <- ggplot(df_ivw, aes(x = group, y = mean, color = method)) +
  geom_point(position = position_dodge(width = 0.5), size = 1.8) +
  geom_errorbar(aes(ymin = lower, ymax = upper), 
                position = position_dodge(width = 0.5), width = 0.2, size = 1) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey50") +
  scale_color_manual(
    values = c("Calibrated" = "#F8766D",  # coral
               "Raw"        = "#00BFC4",  # blue
               "External"   = "#C77CFF")  # purple
  ) +
  ylim(0.7, 1.5) +
  labs(x = expression("Nurture effect sizes (" * r[1] * "," * r[2] * ")"),
       y = "MR Estimates", title = "Trio data: IVW") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.title = element_blank()) 
 # annotate("text", x = 1, y = 1.46, label = "(a)", hjust = 0, size = 4)


p2 <- ggplot(df_mrraps, aes(x = group, y = mean, color = method)) +
  geom_point(position = position_dodge(width = 0.5), size = 1.8) +
  geom_errorbar(aes(ymin = lower, ymax = upper), 
                position = position_dodge(width = 0.5), width = 0.2, size = 1) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey50") +
  scale_color_manual(
    values = c("Calibrated" = "#F8766D",  # coral
               "Raw"        = "#00BFC4",  # blue
               "External"   = "#C77CFF")  # purple
  ) +
  labs(x = expression("Nurture effect sizes (" * r[1] * "," * r[2] * ")"),
       y = "MR Estimates", title = "Trio data: MR.RAPS") +
  ylim(0.7, 1.5) + 
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.title = element_blank()) 
 # annotate("text", x = 1, y = 1.46, label = "(b)", hjust = 0, size = 4)

```

### 2. Sibling linear regression 

```{r  }

dat = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim_parametric202404/sibling_linear_separate/res.mr.rds")

output = c()
for (i in 1:length(dat)){
  cor.y1 = unlist(lapply(dat[[i]]$sim_data.cor_pheno, function(x) x[[1]]))
  cor.y2 = unlist(lapply(dat[[i]]$sim_data.cor_pheno, function(x) x[[2]]))
  
  df = data.frame(cbind(dat[[i]]$sim_data.sig, dat[[i]]$sim_data.r1, dat[[i]]$sim_data.r2,
                        cor.y1, cor.y2, dat[[i]]$fit.method, dat[[1]]$mr.mr_method,
                        dat[[i]]$mr.point_est, dat[[i]]$mr.stderr))
  output = rbind(output, df)
}

colnames(output) = c("sig", "r1", "r2", "phecor.y1", "phecor.y2", 
                     "calibration_method",  "mr_method", "mr.est", "mr.std")

output[, c(1:5, 8:9)] = apply(output[, c(1:5, 8:9)], 2, as.numeric)

dat.ivw = output[output$mr_method == "ivw", ]
dat.mraps = output[output$mr_method == "mr.raps", ]

# select some scenarios for plotting
combination = matrix(NA, ncol = 3, nrow = 5)
colnames(combination) = c("r1", "r2", "sig")
combination[1, ] = c(0, 0, 6)
combination[2, ] = c(0.1, 0.1, 1)
combination[3, ] = c(0.1, 0.5, 1)
combination[4, ] = c(0.5, 0.8, 1)
combination[5, ] = c(0.8, 0.8, 1)

pheno.cor = matrix(NA, ncol = 2, nrow = nrow(combination))
colnames(pheno.cor) = c("Y1", "Y2")
for (i in 1:nrow(combination)){
  dat.sub = dat.ivw[dat.ivw$r1 == combination[i, 1] & dat.ivw$r2 == combination[i, 2]
                     & dat.ivw$sig == combination[i, 3], ]
  cor.y1 = round(mean(dat.sub$phecor.y1, na.rm = TRUE), 2)
  cor.y2 = round(mean(dat.sub$phecor.y2, na.rm = TRUE), 2)
  pheno.cor[i, ] = c(cor.y1, cor.y2)
}

combination2 = data.frame(cbind(combination, pheno.cor))
combination3 <- combination2[order(combination2$Y1, combination2$Y2), ]
```

#### 1. IVW
```{r}
n_rep = 500
res = c()
for (i in 1:nrow(combination3)){
  dat.sub = dat.ivw[dat.ivw$r1 == combination3[i, 1] & dat.ivw$r2 == combination3[i, 2]
                     & dat.ivw$sig == combination3[i, 3], ]
  
  val = cbind(dat.sub$mr.est[dat.sub$calibration_method == "calibrated"][1:n_rep],
              dat.sub$mr.est[dat.sub$calibration_method == "adj_uncalibrated"][1:n_rep],
              dat.sub$mr.est[dat.sub$calibration_method == "unadj_ext"][1:n_rep])
  res = cbind(res, val)
}

means <- colMeans(res)
ses <- apply(res, 2, sd)
vr = rep(NA, nrow(combination3))
for (i in 1:nrow(combination3)){
  indx.cali = (i - 1) * 3 + 1
  indx.raw = (i - 1) * 3 + 2
  vr[i] <- 1-(ses[indx.cali] / ses[indx.raw])^2
}

ncomb <- nrow(combination3)
comb_labels <- paste0("(", combination3$r1, ", ", combination3$r2, ", ", combination3$sig, ")")
phe_labels <- paste0("(", combination3$Y1, ", ", combination3$Y2, ")")

methods <- rep(c("Calibrated", "Raw", "External"), times = ncomb)
group <- rep(comb_labels, each = 3)

df1 <- data.frame(
  method = methods,
  group = factor(group, levels = comb_labels),
  mean = means,   # from IVW
  se = ses
)
df1$method <- factor(df1$method, levels = c("Calibrated", "Raw", "External"))

df1$lower <- df1$mean - 1.96 * df1$se
df1$upper <- df1$mean + 1.96 * df1$se

df2 <- data.frame(
  group = factor(phe_labels, levels = phe_labels),
  vr = vr
)
```

```{r}
p3 <- ggplot(df1, aes(x = group, y = mean, color = method)) +
  geom_point(position = position_dodge(width = 0.5), size = 1.8) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.3,
                position = position_dodge(width = 0.5), size = 1) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey") +
  scale_color_manual(
    values = c(
      "Calibrated" = "#F8766D",  
      "Raw"        = "#00BFC4",  
      "External"   = "#C77CFF"  
    )
  ) +
  labs(x = NULL, y = "MR Estimates", title = "Sibling data: IVW") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


p4 <- ggplot(df2, aes(x = group, y = vr)) +
  geom_point(size = 2) +
  geom_line(group = 1, linetype = "dashed") +
  labs(x = "Sibling phenotypic correlation", y = "Variance reduction") +
  ylim(0, 0.25) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

#### 2. mr.raps
```{r}
n_rep = 500
res = c()
for (i in 1:nrow(combination3)){
  dat.sub = dat.mraps[dat.mraps$r1 == combination3[i, 1] & dat.mraps$r2 == combination3[i, 2]
                     & dat.mraps$sig == combination3[i, 3], ]
  
  val = cbind(dat.sub$mr.est[dat.sub$calibration_method == "calibrated"][1:n_rep],
              dat.sub$mr.est[dat.sub$calibration_method == "adj_uncalibrated"][1:n_rep],
              dat.sub$mr.est[dat.sub$calibration_method == "unadj_ext"][1:n_rep])
  res = cbind(res, val)
}

means <- colMeans(res)
ses <- apply(res, 2, sd)
vr = rep(NA, nrow(combination3))
for (i in 1:nrow(combination3)){
  indx.cali = (i - 1) * 3 + 1
  indx.raw = (i - 1) * 3 + 2
  vr[i] <- 1-(ses[indx.cali] / ses[indx.raw])^2
}

ncomb <- nrow(combination3)
comb_labels <- paste0("(", combination3$r1, ", ", combination3$r2, ", ", combination3$sig, ")")
phe_labels <- paste0("(", combination3$Y1, ", ", combination3$Y2, ")")

methods <- rep(c("Calibrated", "Raw", "External"), times = ncomb)
group <- rep(comb_labels, each = 3)

df1 <- data.frame(
  method = methods,
  group = factor(group, levels = comb_labels),
  mean = means,   # from IVW
  se = ses
)

df1$method <- factor(df1$method, levels = c("Calibrated", "Raw", "External"))

df1$lower <- df1$mean - 1.96 * df1$se
df1$upper <- df1$mean + 1.96 * df1$se


df2 <- data.frame(
  group = factor(phe_labels, levels = phe_labels),
  vr = vr
)
```

```{r}
p5 <- ggplot(df1, aes(x = group, y = mean, color = method)) +
  geom_point(position = position_dodge(width = 0.5), size = 1.8) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.3,
                position = position_dodge(width = 0.5), size = 1) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey") +
  scale_color_manual(
    values = c(
      "Calibrated" = "#F8766D",  
      "Raw"        = "#00BFC4",  
      "External"   = "#C77CFF"  
    )
  ) +
  labs(x = NULL, y = "MR Estimates", title = "Sibling data: MR.RAPS") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


p6 <- ggplot(df2, aes(x = group, y = vr)) +
  geom_point(size = 2) +
  geom_line(group = 1, linetype = "dashed") +
  labs(x = "Sibling phenotypic correlation", y = "Variance reduction") +
  ylim(0, 0.25) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
p1 <- p1 + theme(
  legend.position = c(0.15, 0.85),  # (x, y) relative to plot area
  legend.background = element_rect(fill = alpha('white', 0.6), color = NA),
  legend.key = element_blank()
)

p2 <- p2 + theme(legend.position = "none")
p3 <- p3 + theme(legend.position = "none")
p5 <- p5 + theme(legend.position = "none")

ggsave("/project2/mstephens/yunqiyang/calibrated_mr/simulation-calibrated-mr/output/sim_mr_ggplot2.pdf",
       plot = grid.arrange(p1, p2, p3,p5, p4, p6, ncol = 2),
       width = 10, height = 12)
```









