---
title: "simulation_calibration"
output: html_document
date: '2024-07-15'
---

```{r}
library(latex2exp)
```

```{r}
compute_theo_vr <- function(sigma2, rho, r, b2, sample_size_ratio){
  vr = sigma2*(1-rho)^2*(1-r)/((sigma2 + b2*(1-r^2))*(1+sample_size_ratio - 2*rho))/2
  return(vr)
}

theo_vr = compute_theo_vr(1, 0, 0, 0, 0.1)
```

```{r}
combine_single_snp_stat = function(cond_indx, snp_indx, data.list, column_names){
  res = lapply(cond_indx, function(ind) data.list[[ind]][snp_indx, column_names])
  dat_combined = do.call(rbind, res)
  return(dat_combined)
}
```

```{r}
pdf("/project2/mstephens/yunqiyang/calibrated_mr/simulation-calibrated-mr/output/sim_calibration_lr.pdf", height = 5, width = 8)
par(mfrow = c(1,2))
### Trio data
res = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim_parametric202404/trio_linear/res.rds")

r1 = unique(res$sim_data.r1)
p = 10
empirical_var_raw = matrix(NA, ncol = p, nrow = length(r1))
empirical_var_cali = matrix(NA, ncol = p, nrow = length(r1))

for (i in 1:p){
  # result merged for different r2 values 
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res$sim_data.r1 == r1[k] & res$fit.method == "calibrated_model_T"), i, data.list = res$fit.sumstat, column_names = c("Y1.raw")))
  dat_estimator <- do.call(cbind, snp_dat_list)
  empirical_var_raw[, i] = apply(dat_estimator, 2, var)
  
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res$sim_data.r1 == r1[k] & res$fit.method == "calibrated_model_T"), i, data.list = res$fit.sumstat, column_names = c("Y1.cali")))
  dat_estimator <- do.call(cbind, snp_dat_list)
  empirical_var_cali[, i] = apply(dat_estimator, 2, var)
}

vr = (empirical_var_raw - empirical_var_cali) / empirical_var_raw
rownames(vr) = r1

# Create a vector for equally spaced x-values
x_values = c(1, 2, 3)
plot(x = as.factor(rep(x_values, p)), y = c(vr), xlab = TeX("$r_1$ value"), ylab = "Empirical variance reduction", xaxt="n", pch = 20,ylim = c(0, 1), boxwex = 0.5, main = "Trio data")
axis(1, at = x_values, labels = c("0", "0.1", "0.5"))
abline(h = theo_vr, col = "red", lty = 2)
mtext("(a)", side = 1, line = 4)

### Sibling data
phe_seq = seq(0, 1, by = 0.01)
theo_vr = (1-0.5)/2*(1-phe_seq)/(1+0.5*phe_seq)
res = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim_parametric202404/sibling_linear/res.rds")

p = 10
r1 = unique(res$sim_data.r1)
sigs = unique(res$sim_data.sig)
combinations = expand.grid(r1 = r1, sigs = sigs)
ncomb = nrow(combinations)
combinations$pheno.cor = rep(NA, ncomb)

empirical_var_raw = matrix(NA, ncol = p, nrow = ncomb)
empirical_var_cali = matrix(NA, ncol = p, nrow = ncomb)


for (i in 1:p){
  for (k in 1:nrow(combinations)){
    dat_indx = which(res$sim_data.r1 == combinations[k, 1] & res$sim_data.sig == combinations[k, 2] & res$fit.method == "calibrated")
    combinations[k, 3] = mean(unlist(lapply(res$sim_data.cor_pheno[dat_indx], function(x) x[1])))
    empirical_var_raw[k, i] = var(unlist(lapply(res$fit.sumstat[dat_indx], function(x) x[i, "Y1.raw"])))
    empirical_var_cali[k, i] = var(unlist(lapply(res$fit.sumstat[dat_indx], function(x) x[i, "Y1.cali"])))
  }
}

combinations$pheno.cor = round(combinations$pheno.cor,2)
vr = (empirical_var_raw - empirical_var_cali)/empirical_var_raw
plot(x = rep(combinations$pheno.cor, p), y = c(vr), xlab = "phenotypic correlation", ylab = "Empirical variance reduction", pch = 20, xlim = c(0,0.8), cex = 0.6, main = "Sibling data")
lines(x = phe_seq, y = theo_vr, col = "red", lty = 2)
mtext("(b)", side = 1, line = 4)
```

