---
title: "Calibration result: random genotype"
output: html_document
date: '2024-01-31'
---

### Description: 

Parametric simulation result for calibration. Plot empirical variance for each snp. Combine 10 SNPs into boxplot. 


```{r}
res = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim_parametric202404/trio_linear/res.rds")
```

```{r}
combine_single_snp_stat = function(cond_indx, snp_indx, data.list, column_names){
  res = lapply(cond_indx, function(ind) data.list[[ind]][snp_indx, column_names])
  dat_combined = do.call(rbind, res)
  return(dat_combined)
}
```

### 1. Linear regression: exposure trait. 

```{r }

par(mfrow = c(10,2))
r1 = unique(res$sim_data.r1)
p = 10
empirical_var_raw = matrix(NA, ncol = p, nrow = length(r1))
empirical_var_cali = matrix(NA, ncol = p, nrow = length(r1))

for (i in 1:p){
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res$sim_data.r1 == r1[k] & res$fit.method == "calibrated_model_T"), i, data.list = res$fit.sumstat, column_names = c("Y1.raw")))
  dat_estimator <- do.call(cbind, snp_dat_list)
  empirical_var_raw[, i] = apply(dat_estimator, 2, var)
  
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res$sim_data.r1 == r1[k] & res$fit.method == "calibrated_model_T"), i, data.list = res$fit.sumstat, column_names = c("Y1.cali")))
  dat_estimator <- do.call(cbind, snp_dat_list)
  empirical_var_cali[, i] = apply(dat_estimator, 2, var)
}
```

```{r fig.height = 5, fig.width=4}

vr = (empirical_var_raw - empirical_var_cali) / empirical_var_raw
rownames(vr) = r1

# Create a vector for equally spaced x-values
x_values = c(1, 2, 3)
plot(x = as.factor(rep(x_values, p)), y = c(vr), xlab = "r1 value", ylab = "Empirical variance reduction", xaxt="n", pch = 20,ylim = c(0, 1), boxwex = 0.5)
axis(1, at = x_values, labels = c("0", "0.1", "0.5"))

```

### 2. Linear regression: outcome trait. 

```{r }

p <- 10
r1 <- unique(res$sim_data.r1)
r2 <- unique(res$sim_data.r2)

# Create a data frame of all combinations of r1 and r2
combinations <- expand.grid(r1 = r1, r2 = r2)

# Initialize the matrices for storing variances
empirical_var_raw <- matrix(NA, ncol = p, nrow = nrow(combinations))
empirical_var_cali <- matrix(NA, ncol = p, nrow = nrow(combinations))

for (i in 1:p) {
  snp_dat_list_raw <- lapply(1:nrow(combinations), function(k) {
    subset_index <- which(res$sim_data.r1 == combinations$r1[k] & 
                          res$sim_data.r2 == combinations$r2[k] & 
                          res$fit.method == "calibrated_model_T")
    combine_single_snp_stat(subset_index, i, data.list = res$fit.sumstat, column_names = c("Y1.raw"))
  })
  
  snp_dat_list_cali <- lapply(1:nrow(combinations), function(k) {
    subset_index <- which(res$sim_data.r1 == combinations$r1[k] & 
                          res$sim_data.r2 == combinations$r2[k] & 
                          res$fit.method == "calibrated_model_T")
    combine_single_snp_stat(subset_index, i, data.list = res$fit.sumstat, column_names = c("Y1.cali"))
  })
  
  empirical_var_raw[, i] <- unlist(lapply(snp_dat_list_raw, var))
  empirical_var_cali[, i] <- unlist(lapply(snp_dat_list_cali, var))
}

```


```{r}
vr <- (empirical_var_raw - empirical_var_cali) / empirical_var_raw
combination_labels <- apply(combinations, 1, function(x) paste0("r1=", x[1], ",r2=", x[2]))
x_values = 1:length(combination_labels)
plot(x = as.factor(rep(x_values, p)), c(vr), type = "p",
     xaxt = 'n', xlab = "", ylab = "Empirical variance reduction", pch = 20, ylim = c(0, 1))
axis(side = 1, at = c(1:length(combination_labels)), labels = rep(combination_labels), las = 2, cex.axis = 0.8)
```



### 3. Logistic regression: exposure trait
```{r}
res = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim_parametric202404/trio_logistic_cutoff1.5/res.rds")
```

```{r }

par(mfrow = c(10,2))
r1 = unique(res$sim_data.r1)
p = 10
empirical_var_raw = matrix(NA, ncol = p, nrow = length(r1))
empirical_var_cali = matrix(NA, ncol = p, nrow = length(r1))

for (i in 1:p){
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res$sim_data.r1 == r1[k] & res$fit.method == "calibrated"), i, data.list = res$fit.sumstat, column_names = c("Y1.raw")))
  dat_estimator <- do.call(cbind, snp_dat_list)
  empirical_var_raw[, i] = apply(dat_estimator, 2, var)
  
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res$sim_data.r1 == r1[k] & res$fit.method == "calibrated"), i, data.list = res$fit.sumstat, column_names = c("Y1.cali")))
  dat_estimator <- do.call(cbind, snp_dat_list)
  empirical_var_cali[, i] = apply(dat_estimator, 2, var)
}
```


```{r}
vr = (empirical_var_raw - empirical_var_cali) / empirical_var_raw
rownames(vr) = r1

# Create a vector for equally spaced x-values
x_values = c(1, 2, 3)
plot(x = rep(x_values, p), y = c(vr), xlab = "r1 value", ylab = "Empirical variance reduction", xaxt="n", pch = 20)
axis(1, at = x_values, labels = c("0", "0.1", "0.5"))
```


### 4. Logistic regression: outcome trait. 

```{r }

p <- 10
r1 <- unique(res$sim_data.r1)
r2 <- unique(res$sim_data.r2)

# Create a data frame of all combinations of r1 and r2
combinations <- expand.grid(r1 = r1, r2 = r2)

# Initialize the matrices for storing variances
empirical_var_raw <- matrix(NA, ncol = p, nrow = nrow(combinations))
empirical_var_cali <- matrix(NA, ncol = p, nrow = nrow(combinations))

for (i in 1:p) {
  snp_dat_list_raw <- lapply(1:nrow(combinations), function(k) {
    subset_index <- which(res$sim_data.r1 == combinations$r1[k] & 
                          res$sim_data.r2 == combinations$r2[k] & 
                          res$fit.method == "calibrated")
    combine_single_snp_stat(subset_index, i, data.list = res$fit.sumstat, column_names = c("Y1.raw"))
  })
  
  snp_dat_list_cali <- lapply(1:nrow(combinations), function(k) {
    subset_index <- which(res$sim_data.r1 == combinations$r1[k] & 
                          res$sim_data.r2 == combinations$r2[k] & 
                          res$fit.method == "calibrated")
    combine_single_snp_stat(subset_index, i, data.list = res$fit.sumstat, column_names = c("Y1.cali"))
  })
  
  empirical_var_raw[, i] <- unlist(lapply(snp_dat_list_raw, var))
  empirical_var_cali[, i] <- unlist(lapply(snp_dat_list_cali, var))
}

```


```{r}
vr <- (empirical_var_raw - empirical_var_cali) / empirical_var_raw
combination_labels <- apply(combinations, 1, function(x) paste0("r1=", x[1], ",r2=", x[2]))
x_values = 1:length(combination_labels)
plot(x = rep(x_values, p), c(vr), type = "p",
     xaxt = 'n', xlab = "", ylab = "Empirical variance reduction", pch = 20)
axis(side = 1, at = c(1:length(combination_labels)), labels = rep(combination_labels), las = 2, cex.axis = 0.8)
```



