---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


+ [Test revised calibarted-mr code](test_code.html)

+ [Check variance reduction: Gaussian case](sim_gaussian_res.html)

+ [Check variance reduction: Binomial case](sim_binomial.html)

+ [Check variance reduction empirically](empirical_var_reduction.html)

+ [Real data simulation](sim_real_dat.html)

+ [Perform MR](mr_real_dat.html)

+ [Simulating from Y.pa](simulate_from_par_pheno.html)

+ [Real data analysis](real_data_analysis.html)

Simulation using ukb real genotype

+ [Calibration result: ukb trio](ukb_calibration.html)

+ [Calibration result: ukb trio with resampling](calibration_fixedX.html)


Parametric simulation: 

+ [Calibration result: random X](sim_calibration_randomX.html)

+ [Calibration result on sibling: random X](calibration_sib_randomX.html)

+ [Calibration result: logistic trio](calibration_logistic_trio.html)

+ [Calibration result: logistic sibling](calibration_logistic_sib.html)

+ [Understand bias in logistic regression](logistic_bias.html)

+ [MR bias](mr_bias.html)

+ [MR result: trio data linear regression](mr_result_randomX.html)

+ [MR result: trio data logistic regression](mr_logistic_trio.html)

+ [MR result on sibling: linear regression](mr_result_sib_randomX.html)

+ [MR result on sibling: logistic regression](mr_result_logistic_sib.html)


Parametric simulation combined:

+ [Calibration result: trio data](calibration_trio.html)

+ [Calibration result: sibling data](calibration_sibling.html)

+ [MR result: trio data](mr_trio.html)

+ [MR result: sibling data](mr_sibling.html)

UKB EDA:

+ [EDA on UKB trio data 1](ukb_EDA.html)

+ [EDA on UKB trio data 2](eda_ukb_trio.html)

+ [EDA on UKB external data](eda_ukb_external.html)



UKB data analysis:

+ [UKB trait calibration: check summary stat](check_sumstat.html)

+ [UKB trait calibration result trio](ukb_trait_calibration_trio.html)

+ [UKB trait calibration result sibling](ukb_trait_calibration_sib.html)

+ [genotype convert issue](check_bmi.html)

+ [UKB mr on random sample](ukb_mr_random_sample.html)

+ [UKB calibration result: sanity check](mr_result_check.html)

+ [UKB mr result: trio](ukb_mr_trio.html)

+ [UKB mr result: sibling](ukb_mr_sibling.html)

+ [UKB mr: bmi as exposure (202407)](ukb_mr_bmi_202407.html)

+ [UKB mr: height as exposure (202407)](ukb_mr_height_202407.html)

+ [UKB mr: bmi combined (202407)](real_data_mr_bmi.html)

+ [UKB mr: height combined (202407)](real_data_mr_height.html)

+ [UKB debug: bmi on sbp](sbp_bmi_debug.html)
