---
title: "Mendelian randomization comparison"
author: "Yunqi Yang"
date: "7/19/2023"
output: html_document
---

```{r}
dat = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/simulation/mr_comparison.rds")
```

```{r}
exp_NT_effect = c(0, 0.001, 0.01)
out_NT_effect = c(0.1, 0.5)
method = c("calibrated", "adj_uncalibrated", "unadj_ext", "unadj_int")
mr_method = c("eggr", "ivw", "mr.raps")

```

```{r fig.width=8, fig.height=10}
par(mfrow = c(3,2), mar = c(4, 5, 3, 2) + 0.1, oma = c(3, 1, 0, 0) + 0.1)
for (i in 1:length(exp_NT_effect)){
  for (j in 1:length(out_NT_effect)){
    res = dat[dat$simulate.exp_NT_effect == exp_NT_effect[i] & dat$simulate.out_NT_effect == out_NT_effect[j] & dat$mr.mr_method == "eggr", ]
    val = c(res$mr.point_est[res$fit.method == "calibrated"], 
            res$mr.point_est[res$fit.method == "adj_uncalibrated"],
            res$mr.point_est[res$fit.method == "unadj_ext"],
            res$mr.point_est[res$fit.method == "unadj_int"]
            )
    group = c(rep("cali", 50), rep("uncali", 50), rep("ext", 50), rep("int", 50))
    boxplot(val ~ group, ylab = "Point estimate", main = paste0("egger: exp =", exp_NT_effect[i], "; out =", out_NT_effect[j]))
  }
}
```

```{r fig.width=8, fig.height=8}
par(mfrow = c(3,2), mar = c(4, 5, 3, 2) + 0.1, oma = c(3, 1, 0, 0) + 0.1)
for (i in 1:length(exp_NT_effect)){
  for (j in 1:length(out_NT_effect)){
    res = dat[dat$simulate.exp_NT_effect == exp_NT_effect[i] & dat$simulate.out_NT_effect == out_NT_effect[j] & dat$mr.mr_method == "mr.raps", ]
    val = c(res$mr.point_est[res$fit.method == "calibrated"], 
            res$mr.point_est[res$fit.method == "adj_uncalibrated"],
            res$mr.point_est[res$fit.method == "unadj_ext"],
            res$mr.point_est[res$fit.method == "unadj_int"]
            )
    group = c(rep("cali", 50), rep("uncali", 50), rep("ext", 50), rep("int", 50))
    boxplot(val ~ group, ylab = "Point estimate", main = paste0("mr.raps: exp =", exp_NT_effect[i], "; out =", out_NT_effect[j]))
  }
}
```

```{r fig.width=8, fig.height=8}
par(mfrow = c(3,2), mar = c(4, 5, 3, 2) + 0.1, oma = c(3, 1, 0, 0) + 0.1)
# c(bottom, left, top, right)


for (i in 1:length(exp_NT_effect)){
  for (j in 1:length(out_NT_effect)){
    res = dat[dat$simulate.exp_NT_effect == exp_NT_effect[i] & dat$simulate.out_NT_effect == out_NT_effect[j] & dat$mr.mr_method == "ivw", ]
    val = c(res$mr.point_est[res$fit.method == "calibrated"], 
            res$mr.point_est[res$fit.method == "adj_uncalibrated"],
            res$mr.point_est[res$fit.method == "unadj_ext"],
            res$mr.point_est[res$fit.method == "unadj_int"]
            )
    group = c(rep("cali", 50), rep("uncali", 50), rep("ext", 50), rep("int", 50))
    boxplot(val ~ group, ylab = "Point estimate", main = paste0("IVW: exp =", exp_NT_effect[i], "; out =", out_NT_effect[j]))
  }
}


```


