---
title: "Perform MR to assess causal effect estimate"
author: "Yunqi Yang"
date: "5/15/2023"
output: html_document
---

### Description: 

Perform MR to assess causal effect estimate. We should focus on both effect size estimate and standard error of the causal effect. Here the sample size for external data $N=1e4$ and internal data $n=1e3$. 

```{r}
library(MendelianRandomization)
dat = readRDS("./data/realdata.rds")
source("./code/calibrated_mr.R")
```

### Compute raw and calibrated estimator for each SNP
```{r}
n = 1e3
p = 1e3
N = 1e4

y1.cali <- matrix(NA, nrow = p, ncol = 2)
y1.raw <- matrix(NA, nrow = p, ncol = 2)
colnames(y1.cali) <- c("point_estimate", "var_estimate")
colnames(y1.raw) <- c("point_estimate", "var_estimate")

y2.cali <- matrix(NA, nrow = p, ncol = 2)
y2.raw <- matrix(NA, nrow = p, ncol = 2)
colnames(y2.cali) <- c("point_estimate", "var_estimate")
colnames(y2.raw) <- c("point_estimate", "var_estimate")
```


```{r }
for (i in 1:p){
  dat1_valid <- cbind(dat[["pheno"]][1:n,1], dat[["trans"]][1:n, i], dat[["nontrans"]][1:n, i]) 
  dat1_ext <- cbind(dat[["pheno"]][,1], dat[["trans"]][, i]) 
  
  coef_ext <- compute_sumstat(dat1_ext[,1], dat1_ext[,2])$bhat
  res_int <- compute_sumstat(dat1_valid[,1], dat1_valid[,2])
  res_int_adj <- compute_adj_sumstat(dat1_valid[,1], dat1_valid[,2], dat1_valid[,3])
  res1 <- calibrated_estimator(dat1_valid, N, res_int$resid, res_int_adj$resid, res_int$bhat, res_int_adj$bhat, coef_ext)

  
  # Select different samples for outcome trait. 
  dat2_valid <- cbind(dat[["pheno"]][(1+1e3):(n+1e3),2], dat[["trans"]][(1+1e3):(n+1e3), i], dat[["nontrans"]][(1+1e3):(n+1e3), i]) 
  dat2_ext <- cbind(dat[["pheno"]][, 2], dat[["trans"]][, i]) 
  
  coef_ext <- compute_sumstat(dat2_ext[,1], dat2_ext[,2])$bhat
  res_int <- compute_sumstat(dat2_valid[,1], dat2_valid[,2])
  res_int_adj <- compute_adj_sumstat(dat2_valid[,1], dat2_valid[,2], dat2_valid[,3])
  res2 <- calibrated_estimator(dat2_valid, N, res_int$resid, res_int_adj$resid, res_int$bhat, res_int_adj$bhat, coef_ext)
  
  
  y1.cali[i, ] = c(res1$tau_cal, res1$var_tau_cal)
  y2.cali[i, ] = c(res2$tau_cal, res2$var_tau_cal)
  y1.raw[i, ] = c(res1$tau_raw, res1$var_tau_raw)
  y2.raw[i, ] = c(res2$tau_raw, res2$var_tau_raw)
}

head(y1.cali)
head(y1.raw)
head(y2.cali)
head(y2.raw)
```





```{r }
par(mfrow = c(1,2))
plot(y1.cali[,2], y1.raw[,2], pch = 20, xlab = "calibrated estimator", ylab = "raw estimator",  main = "SNP variance: exposure trait")
abline(a = 0, b = 1, col = "red")

plot(y2.cali[,2], y2.raw[,2], pch = 20, xlab = "calibrated estimator", ylab = "raw estimator", main = "SNP variance: outcome trait")
abline(a = 0, b = 1, col = "red")
```

### Perform different MR methods to assess the causal effect estimate.
```{r}

MRInput.cali <- mr_input(bx = y1.cali[,1],
                          bxse = y1.cali[,2],
                          by = y2.cali[,1],
                          byse = y2.cali[,2])

MRInput.raw <- mr_input(bx = y1.raw[,1],
                          bxse = y1.raw[,2],
                          by = y2.raw[,1],
                          byse = y2.raw[,2])


egger.cali <- mr_egger(MRInput.cali)
egger.raw <- mr_egger(MRInput.raw)

ivw.cali <- mr_ivw(MRInput.cali)
ivw.raw <- mr_ivw(MRInput.raw)
```

```{r}
egger.cali
egger.raw
ivw.cali
ivw.raw
```

