---
title: "MR: real data"
author: "Yunqi Yang"
date: "9/13/2023"
output: html_document
---

```{r}
library(mr.raps)
library(GRAPPLE)
library(MendelianRandomization)
```

### 1. BMI on education attainment

```{r}
sel.file <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/BMI-giant17eu.csv"
exp.file <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/BMI-ukb.csv"

exp.file <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/BMI-giant17eu.csv"
out.file <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/GWAS_EA_excl23andMe.txt"
plink_refdat <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/data_maf0.01_rs_ref/data_maf0.01_rs_ref"

data.list <- getInput(sel.file, exp.file, out.file, plink_refdat, max.p.thres = 0.01, 
                      plink_exe = '/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/plink_mac_20230116/plink')

```

```{r}
write.table(data.list$data[, 1], "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/dat_ukb/bmi_ea.txt", quote = FALSE, col.names  = FALSE, row.names = FALSE)
```

```{r, fig.width=8, fig.height=6}
par(mfrow = c(1,3))
pval_threshold = c(1e-4, 1e-6, 1e-8)
for (i in 1:length(pval_threshold)){
  dat = data.list$data[data.list$data$selection_pvals < pval_threshold[i], ]
  MRInput <- mr_input(bx = dat$gamma_exp1,
                    bxse = dat$se_exp1,
                    by = dat$gamma_out1,
                    byse = dat$se_out1)
  
  res.egger <- mr_egger(MRInput)
  res.ivw <- mr_ivw(MRInput)
  res.mrraps = mr.raps.mle(dat$gamma_exp1,
                         dat$gamma_out1, 
                         dat$se_exp1, 
                         dat$se_out1)
  

  means = c(res.ivw@Estimate, res.egger@Estimate, res.mrraps$beta.hat)
  ci.lower = c(res.ivw@CILower, res.egger@CILower.Est, res.mrraps$beta.hat - 1.96*res.mrraps$beta.se)
  ci.upper = c(res.ivw@CIUpper, res.egger@CIUpper.Est, res.mrraps$beta.hat + 1.96*res.mrraps$beta.se) 
    
  # Create a vector for group names (optional)
  groups <- c("ivw", "egger", "mr.raps")
  plot(1:length(means), means, type = "n", xaxt = "n", ylim = c(min(ci.lower), max(ci.upper) + 0.1),
         xlab = "Group", ylab = "Value", main = paste0("BMI on EA: pval=",pval_threshold[i]))

  points(1:length(means), means, pch = 19, col = "blue")

  # Add confidence intervals as line segments
  segments(1:length(means), ci.lower, 1:length(means), ci.upper, col = "red")
    
  # Add group names to the x-axis (optional)
  axis(1, at = 1:length(means), labels = groups)
    
  # Add a legend
  legend("topright", legend = c("Point Estimate", "Confidence Interval"), 
           pch = c(19, NA), col = c("blue", "red"), lty = c(NA, 1), bty = "n")

}
```



### 2. BMI on T2D

```{r}
sel.file <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/BMI-giant17eu.csv"
exp.file <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/BMI-ukb.csv"
out.file <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/T2D-diagram12-Im.csv"
plink_refdat <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/data_maf0.01_rs_ref/data_maf0.01_rs_ref"

data.list <- getInput(sel.file, exp.file, out.file, plink_refdat, max.p.thres = 0.01, 
                      plink_exe = '/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/plink_mac_20230116/plink')

```

```{r}
write.table(data.list$data[,1], "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/dat_ukb/bmi_t2d.txt", quote = FALSE, col.names  = FALSE, row.names = FALSE)
```


```{r, fig.width=8, fig.height=6}
par(mfrow = c(1,3))
pval_threshold = c(1e-4, 1e-6, 1e-8)
for (i in 1:length(pval_threshold)){
  dat = data.list$data[data.list$data$selection_pvals < pval_threshold[i], ]
  MRInput <- mr_input(bx = dat$gamma_exp1,
                    bxse = dat$se_exp1,
                    by = dat$gamma_out1,
                    byse = dat$se_out1)
  
  res.egger <- mr_egger(MRInput)
  res.ivw <- mr_ivw(MRInput)
  res.mrraps = mr.raps.mle(dat$gamma_exp1,
                         dat$gamma_out1, 
                         dat$se_exp1, 
                         dat$se_out1)
  

  means = c(res.ivw@Estimate, res.egger@Estimate, res.mrraps$beta.hat)
  ci.lower = c(res.ivw@CILower, res.egger@CILower.Est, res.mrraps$beta.hat - 1.96*res.mrraps$beta.se)
  ci.upper = c(res.ivw@CIUpper, res.egger@CIUpper.Est, res.mrraps$beta.hat + 1.96*res.mrraps$beta.se) 
    
  # Create a vector for group names (optional)
  groups <- c("ivw", "egger", "mr.raps")
  plot(1:length(means), means, type = "n", xaxt = "n", ylim = c(-2, 2),
         xlab = "Group", ylab = "Value", main = paste0("BMI on T2D: pval=",pval_threshold[i])) 

  points(1:length(means), means, pch = 19, col = "blue")

  # Add confidence intervals as line segments
  segments(1:length(means), ci.lower, 1:length(means), ci.upper, col = "red")
    
  # Add group names to the x-axis (optional)
  axis(1, at = 1:length(means), labels = groups)
    
  # Add a legend
  legend("topright", legend = c("Point Estimate", "Confidence Interval"), 
           pch = c(19, NA), col = c("blue", "red"), lty = c(NA, 1), bty = "n")

}
```


### 3. height on EA

```{r}

sel.file <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/Height-giant14.csv"
exp.file <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/height-ukb.csv"
out.file <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/GWAS_EA_excl23andMe.txt"
plink_refdat <- "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/data_maf0.01_rs_ref/data_maf0.01_rs_ref"

data.list <- getInput(sel.file, exp.file, out.file, plink_refdat, max.p.thres = 0.01, 
                      plink_exe = '/Users/nicholeyang/Downloads/calibrated_estimator/simulation/real_data/plink_mac_20230116/plink')

```

```{r}
write.table(data.list$data[,1], "/Users/nicholeyang/Downloads/calibrated_estimator/simulation/dat_ukb/height_ea.txt", quote = FALSE, col.names  = FALSE, row.names = FALSE)
```

```{r, fig.width=8, fig.height=6}
par(mfrow = c(1,3))
pval_threshold = c(1e-4, 1e-6, 1e-8)
for (i in 1:length(pval_threshold)){
  dat = data.list$data[data.list$data$selection_pvals < pval_threshold[i], ]
  MRInput <- mr_input(bx = dat$gamma_exp1,
                    bxse = dat$se_exp1,
                    by = dat$gamma_out1,
                    byse = dat$se_out1)
  
  res.egger <- mr_egger(MRInput)
  res.ivw <- mr_ivw(MRInput)
  res.mrraps = mr.raps.mle(dat$gamma_exp1,
                         dat$gamma_out1, 
                         dat$se_exp1, 
                         dat$se_out1)
  

  means = c(res.ivw@Estimate, res.egger@Estimate, res.mrraps$beta.hat)
  ci.lower = c(res.ivw@CILower, res.egger@CILower.Est, res.mrraps$beta.hat - 1.96*res.mrraps$beta.se)
  ci.upper = c(res.ivw@CIUpper, res.egger@CIUpper.Est, res.mrraps$beta.hat + 1.96*res.mrraps$beta.se) 
    
  # Create a vector for group names (optional)
  groups <- c("ivw", "egger", "mr.raps")
  plot(1:length(means), means, type = "n", xaxt = "n", ylim = c(-0.02, 0.1),
         xlab = "Group", ylab = "Value", main = paste0("Height on EA: pval=",pval_threshold[i]))

  points(1:length(means), means, pch = 19, col = "blue")

  # Add confidence intervals as line segments
  segments(1:length(means), ci.lower, 1:length(means), ci.upper, col = "red")
    
  # Add group names to the x-axis (optional)
  axis(1, at = 1:length(means), labels = groups)
    
  # Add a legend
  legend("topright", legend = c("Point Estimate", "Confidence Interval"), 
           pch = c(19, NA), col = c("blue", "red"), lty = c(NA, 1), bty = "n")

}
```

