---
title: "Calibration on ukb sibling data"
author: "Yunqi Yang"
date: "5/8/2024"
output: html_document
---

### 1. BMI

```{r}
sumstat = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_bmi.rds")
ext = read.csv("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/combined_bmi.linear", sep = "\t")
```


```{r}
sumstat = as.data.frame(sumstat)
sumstat[, c(3:8)] = apply(sumstat[, c(3:8)], 2, as.numeric)
dat = merge(sumstat, ext, by.x = "variant", by.y = "ID", all = FALSE)
# flip sign of effect if the allele tested is different
dat$BETA = ifelse(dat$allele.test == dat$A1, dat$BETA, -dat$BETA)
```

```{r fig.width=8, fig.height=8}
# check estimate scale
par(mfrow = c(2,2))

plot(dat$cali, dat$raw, xlab = "calibrated estimator", ylab = "uncalibrated estimator")
abline(a = 0, b = 1, col = "red")
plot(dat$BETA, dat$int, xlab = "external gwas", ylab = "internal gwas")
abline(a = 0, b = 1, col = "red")

hist(dat$cali - dat$raw, main = "Differece: calibrated estimator - uncalibrated estimator", xlab = "")
hist(dat$int - dat$BETA, main = "Difference: internal gwas - external gwas", xlab = "")

```

```{r }
pval.ext = pnorm(abs(dat$BETA/dat$SE), lower.tail = FALSE)
pval.cali = pnorm(abs(dat$cali/sqrt(dat$cali.var)), lower.tail = FALSE)
pval.uncali = pnorm(abs(dat$raw/sqrt(dat$raw.var)), lower.tail = FALSE)

sum(pval.ext < 1e-8)
sum(pval.cali < 1e-3)
sum(pval.uncali < 1e-3)
```

#### Calibration result

```{r fig.width=10, fig.height=6}
par(mfrow = c(1, 2))
boxplot(dat[, c("cali.var", "raw.var")], ylab = "variance")
vr = (dat$raw.var - dat$cali.var)/dat$raw.var
mean(vr)
hist(vr, main = "variance reduction", xlab = "")
```





### 2. DBP

```{r}
sumstat = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_dbp.rds")
ext = read.csv("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/combined_dbp.linear", sep = "\t")
```


```{r}
sumstat = as.data.frame(sumstat)
sumstat[, c(3:8)] = apply(sumstat[, c(3:8)], 2, as.numeric)
dat = merge(sumstat, ext, by.x = "variant", by.y = "ID", all = FALSE)
# flip sign of effect if the allele tested is different
dat$BETA = ifelse(dat$allele.test == dat$A1, dat$BETA, -dat$BETA)
```

```{r fig.width=8, fig.height=8}
# check estimate scale
par(mfrow = c(2,2))

plot(dat$cali, dat$raw, xlab = "calibrated estimator", ylab = "uncalibrated estimator")
abline(a = 0, b = 1, col = "red")
plot(dat$BETA, dat$int, xlab = "external gwas", ylab = "internal gwas")
abline(a = 0, b = 1, col = "red")

hist(dat$cali - dat$raw, main = "Differece: calibrated estimator - uncalibrated estimator", xlab = "")
hist(dat$int - dat$BETA, main = "Difference: internal gwas - external gwas", xlab = "")
cor(dat$cali, dat$raw)
cor(dat$BETA, dat$int)
```

```{r }
pval.ext = pnorm(abs(dat$BETA/dat$SE), lower.tail = FALSE)
pval.cali = pnorm(abs(dat$cali/sqrt(dat$cali.var)), lower.tail = FALSE)
pval.uncali = pnorm(abs(dat$raw/sqrt(dat$raw.var)), lower.tail = FALSE)

sum(pval.ext < 1e-8)
sum(pval.cali < 1e-3)
sum(pval.uncali < 1e-3)
```

#### Calibration result

```{r fig.width=10, fig.height=6}
par(mfrow = c(1, 2))
boxplot(dat[, c("cali.var", "raw.var")], ylab = "variance")
vr = (dat$raw.var - dat$cali.var)/dat$raw.var
mean(vr)
```


### 3. SBP

```{r}
sumstat = readRDS("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/result/sib_calibration_sbp.rds")
ext = read.csv("/Users/nicholeyang/Downloads/calibrated_estimator/real-data-analysis/combined_sbp.linear", sep = "\t")
```


```{r}
sumstat = as.data.frame(sumstat)
sumstat[, c(3:8)] = apply(sumstat[, c(3:8)], 2, as.numeric)
dat = merge(sumstat, ext, by.x = "variant", by.y = "ID", all = FALSE)
# flip sign of effect if the allele tested is different
dat$BETA = ifelse(dat$allele.test == dat$A1, dat$BETA, -dat$BETA)
```

```{r fig.width=8, fig.height=8}
# check estimate scale
par(mfrow = c(2,2))

plot(dat$cali, dat$raw, xlab = "calibrated estimator", ylab = "uncalibrated estimator")
abline(a = 0, b = 1, col = "red")
plot(dat$BETA, dat$int, xlab = "external gwas", ylab = "internal gwas")
abline(a = 0, b = 1, col = "red")

hist(dat$cali - dat$raw, main = "Differece: calibrated estimator - uncalibrated estimator", xlab = "")
hist(dat$int - dat$BETA, main = "Difference: internal gwas - external gwas", xlab = "")
cor(dat$cali, dat$raw)
cor(dat$BETA, dat$int)
```

```{r }
pval.ext = pnorm(abs(dat$BETA/dat$SE), lower.tail = FALSE)
pval.cali = pnorm(abs(dat$cali/sqrt(dat$cali.var)), lower.tail = FALSE)
pval.uncali = pnorm(abs(dat$raw/sqrt(dat$raw.var)), lower.tail = FALSE)

sum(pval.ext < 1e-8)
sum(pval.cali < 1e-3)
sum(pval.uncali < 1e-3)
```

#### Calibration result

```{r fig.width=10, fig.height=6}
par(mfrow = c(1, 2))
boxplot(dat[, c("cali.var", "raw.var")], ylab = "variance")
vr = (dat$raw.var - dat$cali.var)/dat$raw.var
mean(vr)
```


