---
title: "ukb_calibration"
author: "Yunqi Yang"
date: "1/19/2024"
output: html_document
---

### Simulation model and setting:

1. $p = 10$

2. $b, b_p$ are fixed. 

$$
\begin{split}
b^p&\sim N(0, 1),\quad \epsilon\sim N(0, 1)\\
Y^p &= G^pb^p+\epsilon
\end{split}
$$

**Children exposure & outcome traits**

$\beta$ denotes the causal effect. $T$ denotes transmitted allele matrix, and $NT$ denotes non-transmitted allele matrix. 
$$
\begin{split}
\beta & =1\\
b&\sim N(0, 1), \quad \epsilon\sim N(0, 1)\\
Y_1 &= Tb + r_1(Y^m+Y^f) + \epsilon\\
Y_2 &= \beta Y_1 + r_2(Y^m + Y^f) + \epsilon
\end{split}
$$
```{r eval = FALSE}
set.seed(1)
p = 10
b = matrix(rnorm(p, sd = 1), ncol = 1, nrow = p)
bp = matrix(rnorm(p, sd = 1), ncol = 1, nrow = p)
```

```{r}
res1 = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/simulation-calibrated-mr/data/simulation202401/res.rds") # previous simulation result
res2 = readRDS("/project2/mstephens/yunqiyang/calibrated_mr/sim202401/res.rds") # current result
res.Y1 = res1[[1]]
res2.Y1 = res2[[1]]
```

```{r}
combine_single_snp_stat = function(cond_indx, snp_indx, data.list, column_names){
  res = lapply(cond_indx, function(ind) data.list[[ind]][snp_indx, column_names])
  dat_combined = do.call(rbind, res)
  return(dat_combined)
}
```


### 1. Previous simulation results

```{r fig.width=8, fig.height=40}

par(mfrow = c(10,2))
r1 = unique(res.Y1$sim_data.r1)
p = 10
for (i in 1:p){
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res.Y1$sim_data.r1 == r1[k]), i, data.list =res.Y1$calibration.Y1_cali, column_names = c("tau_cal", "tau_raw")))

  dat_estimator <- do.call(cbind, snp_dat_list)
  colors <- rep(c("lightblue", "gold1"), length.out = ncol(dat_estimator))
  boxplot(dat_estimator,
          #main = paste0("Exposure trait, r1=", r1[k]),
          xlab = "r1",
          ylab = "(un)calibrated estimator",
          col = colors,
          outpch = 20, # This changes the outlier point type to solid circle
          outcex = 0.5,
          xaxt = "n")
  points(1:ncol(dat_estimator), colMeans(dat_estimator), pch = 4, cex = 0.8, col = "red2")
  legend("topright",
       legend = c("Calibrated Estimator", "Uncalibrated Estimator", "Empirical mean"),
       fill = c("lightblue", "gold1", NA),  
       pch = c(NA, NA, 4),  
       col = c(NA, NA, "red2"),  
       cex = 0.6)  
  axis(1, at=seq(1.5, by=2, length.out=length(r1)), labels=r1)

  
  ### Plot variance
  empirical_var = apply(dat_estimator, 2, var)
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res.Y1$sim_data.r1 == r1[k]), i, data.list =res.Y1$calibration.Y1_cali, column_names = c("var_tau_cal", "var_tau_raw")))
  dat_estimator_var <- do.call(cbind, snp_dat_list)
    
  colors <- rep(c("lightblue", "gold1"), length.out = ncol(dat_estimator_var))
  boxplot(dat_estimator_var,
          #main = paste0("Exposure trait, r1=", r1[k]),
          ylim = c(0, max(dat_estimator_var) + 0.01),
          xlab = "r1",
          ylab = "Variance of (un)calibrated estimator",
          col = colors,
          outpch = 20, 
          outcex = 0.5,
          xaxt = "n")
  points(1:ncol(dat_estimator_var), empirical_var, pch = 4, cex = 0.8, col = "red2")
  legend("topright",
       legend = c("Calibrated Estimator", "Uncalibrated Estimator", "Empirical variance"),
       fill = c("lightblue", "gold1", NA),  
       pch = c(NA, NA, 4),  
       col = c(NA, NA, "red2"),  
       cex = 0.6)  
  r_values <- c(-0.20, -0.10, 0.00, 0.05, 0.10, 0.50) 
  axis(1, at=seq(1.5, by=2, length.out=length(r1)), labels=r1)
}

```


### 2. Current simulation results

#### 2.1 Multiple effects:

```{r eval = FALSE}
set.seed(1)
p = 10
b = matrix(rnorm(p, sd = 1), ncol = 1, nrow = p)
bp = matrix(rnorm(p, sd = 1), ncol = 1, nrow = p)
```

```{r fig.width=8, fig.height=40}
par(mfrow = c(10,2))
r1 = unique(res2.Y1$sim_data.r1)

for (i in 1:p){
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res2.Y1$sim_data.r1 == r1[k] & res2.Y1$sim_effect.effect_type == "multiple"), i, data.list =res2.Y1$calibration.Y1_cali, column_names = c("tau_cal", "tau_raw")))

  dat_estimator <- do.call(cbind, snp_dat_list)
  colors <- rep(c("lightblue", "gold1"), length.out = ncol(dat_estimator))
  boxplot(dat_estimator,
          #main = paste0("Exposure trait, r1=", r1[k]),
          xlab = "r1",
          ylab = "(un)calibrated estimator",
          col = colors,
          outpch = 20, # This changes the outlier point type to solid circle
          outcex = 0.5,
          xaxt = "n")
  points(1:ncol(dat_estimator), colMeans(dat_estimator), pch = 4, cex = 0.8, col = "red2")
  legend("topright",
       legend = c("Calibrated Estimator", "Uncalibrated Estimator", "Empirical mean"),
       fill = c("lightblue", "gold1", NA),  
       pch = c(NA, NA, 4),  
       col = c(NA, NA, "red2"),  
       cex = 0.6)  
  axis(1, at=seq(1.5, by=2, length.out=length(r1)), labels=r1)

  
  ### Plot variance
  empirical_var = apply(dat_estimator, 2, var)
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res2.Y1$sim_data.r1 == r1[k] & res2.Y1$sim_effect.effect_type == "multiple"), i, data.list =res2.Y1$calibration.Y1_cali, column_names = c("var_tau_cal", "var_tau_raw")))
  dat_estimator_var <- do.call(cbind, snp_dat_list)
    
  colors <- rep(c("lightblue", "gold1"), length.out = ncol(dat_estimator_var))
  boxplot(dat_estimator_var,
          #main = paste0("Exposure trait, r1=", r1[k]),
          ylim = c(0, 0.06),
          xlab = "r1",
          ylab = "Variance of (un)calibrated estimator",
          col = colors,
          outpch = 20, 
          outcex = 0.5,
          xaxt = "n")
  points(1:ncol(dat_estimator_var), empirical_var, pch = 4, cex = 0.8, col = "red2")
  legend("topright",
       legend = c("Calibrated Estimator", "Uncalibrated Estimator", "Empirical variance"),
       fill = c("lightblue", "gold1", NA),  
       pch = c(NA, NA, 4),  
       col = c(NA, NA, "red2"),  
       cex = 0.6)  
  r_values <- c(-0.20, -0.10, 0.00, 0.05, 0.10, 0.50) 
  axis(1, at=seq(1.5, by=2, length.out=length(r1)), labels=r1)
}

```

```{r fig.width=10, fig.height=40}
par(mfrow = c(10,2))
r1 = unique(res2.Y1$sim_data.r1)

for (i in 1:p){
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res2.Y1$sim_data.r1 == r1[k] & res2.Y1$sim_effect.effect_type == "single"), i, data.list =res2.Y1$calibration.Y1_cali, column_names = c("tau_cal", "tau_raw")))

  dat_estimator <- do.call(cbind, snp_dat_list)
  colors <- rep(c("lightblue", "gold1"), length.out = ncol(dat_estimator))
  boxplot(dat_estimator,
          #main = paste0("Exposure trait, r1=", r1[k]),
          xlab = "r1",
          ylab = "(un)calibrated estimator",
          col = colors,
          outpch = 20, # This changes the outlier point type to solid circle
          outcex = 0.5,
          xaxt = "n")
  points(1:ncol(dat_estimator), colMeans(dat_estimator), pch = 4, cex = 0.8, col = "red2")
  legend("topright",
       legend = c("Calibrated Estimator", "Uncalibrated Estimator", "Empirical mean"),
       fill = c("lightblue", "gold1", NA),  
       pch = c(NA, NA, 4),  
       col = c(NA, NA, "red2"),  
       cex = 0.6)  
  axis(1, at=seq(1.5, by=2, length.out=length(r1)), labels=r1)

  
  ### Plot variance
  empirical_var = apply(dat_estimator, 2, var)
  snp_dat_list = lapply(1:length(r1), function(k) combine_single_snp_stat(which(res2.Y1$sim_data.r1 == r1[k] & res2.Y1$sim_effect.effect_type == "single"), i, data.list =res2.Y1$calibration.Y1_cali, column_names = c("var_tau_cal", "var_tau_raw")))
  
  
  dat_estimator_var <- do.call(cbind, snp_dat_list)
    
  colors <- rep(c("lightblue", "gold1"), length.out = ncol(dat_estimator_var))
  boxplot(dat_estimator_var,
          #main = paste0("Exposure trait, r1=", r1[k]),
          ylim = c(0, 0.06),
          xlab = "r1",
          ylab = "Variance of (un)calibrated estimator",
          col = colors,
          outpch = 20, 
          outcex = 0.5,
          xaxt = "n")
  points(1:ncol(dat_estimator_var), empirical_var, pch = 4, cex = 0.8, col = "red2")
  legend("topright",
       legend = c("Calibrated Estimator", "Uncalibrated Estimator", "Empirical variance"),
       fill = c("lightblue", "gold1", NA),  
       pch = c(NA, NA, 4),  
       col = c(NA, NA, "red2"),  
       cex = 0.6)  
  r_values <- c(-0.20, -0.10, 0.00, 0.05, 0.10, 0.50) 
  axis(1, at=seq(1.5, by=2, length.out=length(r1)), labels=r1)
}

```


```{r eval = FALSE}
par(mfrow = c(1,2))
r1 = unique(res.Y1$sim_data.r1)
for (k in 1:length(r1)){
  cond_indx = which(res.Y1$sim_data.r1 == r1[k])
  
  ### Plot mean
  snp_dat_list = lapply(1:p, function(i) 
  
  dat_estimator <- do.call(cbind, snp_dat_list)
  print(dat_estimator)
  colors <- rep(c("lightblue", "gold1"), length.out = ncol(dat_estimator))
  boxplot(dat_estimator,
          main = paste0("Exposure trait, r1=", r1[k]),
          xlab = "",
          ylab = "(un)calibrated estimator",
          col = colors,
          outpch = 20, # This changes the outlier point type to solid circle
          outcex = 0.5,
          xaxt = "n")
  # Add true b to plot
  b.true <- unlist(lapply(1:p, function(i) rep(b[i],2)))
  empirical_var = apply(dat_estimator, 2, var)
  points(1:ncol(dat_estimator), b.true, pch = 4, cex = 0.8, col = "red2")
  legend("topright",
       legend = c("Calibrated Estimator", "Uncalibrated Estimator", "True effect size"),
       fill = c("lightblue", "gold1", NA),  
       pch = c(NA, NA, 4),  
       col = c(NA, NA, "red2"),  
       cex = 0.6)  

# Plot variance
  
  ### Plot variance
  snp_dat_list = lapply(1:p, function(i) combine_single_snp_stat(cond_indx, i, data.list =res.Y1$calibration.Y1_cali, column_names = c("var_tau_cal", "var_tau_raw")))
  dat_estimator_var <- do.call(cbind, snp_dat_list)
  
  colors <- rep(c("lightblue", "gold1"), length.out = ncol(dat_estimator_var))
  boxplot(dat_estimator_var,
          main = paste0("Exposure trait, r1=", r1[k]),
          ylim = c(0, 0.06),
          xlab = "",
          ylab = "Variance of (un)calibrated estimator",
          col = colors,
          outpch = 20, 
          outcex = 0.5,
          xaxt = "n")
  points(1:ncol(dat_estimator_var), empirical_var, pch = 4, cex = 0.8, col = "red2")
  legend("topright",
       legend = c("Calibrated Estimator", "Uncalibrated Estimator", "Empirical variance"),
       fill = c("lightblue", "gold1", NA),  
       pch = c(NA, NA, 4),  
       col = c(NA, NA, "red2"),  
       cex = 0.6)  
}

```








```{r eval = FALSE}
res = readRDS("./data/simulation202401/res.rds")

r1 = c(-0.2, -0.1, 0, 0.05, 0.1, 0.5)
r2 = c(-0.5, -0.1, 0.1, 0.5, 1)

setting = c()
for (i in 1:length(r2)){
  for (j in 1:length(r1)){
    s = paste0( "r2=", r2[i], ",r1=", r1[j])
    setting = c(setting, s)
  }
}

for (i in 1:length(setting)){
  dat = res$calibration.Y1_cali[[i]]
  var_reduction = (dat[,4] - dat[, 3])/dat[,4]
  plot(var_reduction, ylab = setting[i], main = "Exposure trait")
}

dat_var_reduction = matrix(NA, ncol = length(res$calibration.Y1_cali), nrow = 10)
for (i in 1:length(setting)){
  dat = res$calibration.Y1_cali[[i]]
  var_reduction = (dat[,4] - dat[, 3])/dat[,4]
  dat_var_reduction[, i] = var_reduction
}

boxplot(dat_var_reduction, main = "exposure trait")

```



